<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="collision_multiplier" value="1.5" />

    <xacro:property name="limit_effort" value="100" />
    <xacro:property name="limit_velocity" value="10" />

    <xacro:property name="bucket_length" value="0.3556" /> <!-- depth -->
    <xacro:property name="bucket_height" value="0.254" />
    <xacro:property name="bucket_width" value="0.254" />

    <xacro:property name="bucket_frame_length" value="0.1524" /> <!-- depth -->
    <xacro:property name="bucket_frame_height" value="0.4064" />
    <xacro:property name="bucket_frame_width" value="${chassis_width}" />
    <xacro:property name="bucket_frame_offset" value="${chassis_length/2 + buckets_width/10}" />

    <xacro:property name="chassis_length" value="0.8128" />
    <xacro:property name="chassis_height" value="0.0889" />
    <xacro:property name="chassis_width" value="0.3556" />

    <xacro:property name="lidar_length" value="0.12954" />
    <xacro:property name="lidar_height" value="0.07874" />
    <xacro:property name="lidar_width" value="0.09906" />

    <xacro:property name="mesh_scale" value="0.001 0.001 0.001" />

    <xacro:property name="wheel_gap" value="0.0127" />
    <xacro:property name="wheel_length" value="0.1016" />
    <xacro:property name="wheel_radius" value="0.14224" />
    <xacro:property name="wheel_mass" value="0.0624" />
    <xacro:property name="wheel_mesh_file" value="file://$(find osprey_ros)/meshes/robot24/wheel.dae" />
    <xacro:property name="wheel_offset_front" value="${chassis_length/2 - 0.1024}" />
    <xacro:property name="wheel_offset_rear" value="${-chassis_length/2 + 0.1024}" />
    <xacro:property name="wheel_offset_side" value="${wheel_length/2 + chassis_width/2 + wheel_gap}" />

    <link name="base_link"></link>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
    </joint>
    <link name="base_footprint">
        <parent link="base_link"/>
    </link>

    <!-- Main Body/Chassis -->
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
        <child link="chassis"/>
    </joint>
    <link name="chassis">
        <collision>
            <geometry>
                <box size="${chassis_length * collision_multiplier} ${chassis_width * collision_multiplier} ${chassis_height}"/>
            </geometry>
        </collision>
        <visual>
            <geometry>
                <mesh filename="file://$(find osprey_ros)/meshes/robot24/chassis.dae" scale="${mesh_scale}" />
            </geometry>
            <material name="gray"/>
        </visual>
        <xacro:inertial_box mass="2.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- Front Left Wheel -->
    <joint name="front_left_wheel_joint" type="continuous">
        <parent link="chassis"/>
        <child link="front_left_wheel"/>
        <origin xyz="${wheel_offset_front} ${wheel_offset_side} 0" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
        <limit effort="${limit_effort}" velocity="${limit_velocity}"/>
    </joint>
    <link name="front_left_wheel">
        <collision>
            <geometry>
                <cylinder length="${wheel_length * collision_multiplier}" radius="${wheel_radius}" />
            </geometry>
        </collision>
        <visual>
            <origin xyz="0 0 ${wheel_length/2}" rpy="-${pi/2} 0 0"/>
            <geometry>
                <mesh filename="${wheel_mesh_file}" scale="${mesh_scale}" />
            </geometry>
            <material name="gray"/>
        </visual>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Front Right Wheel -->
    <joint name="front_right_wheel_joint" type="continuous">
        <parent link="chassis"/>
        <child link="front_right_wheel"/>
        <origin xyz="${wheel_offset_front} -${wheel_offset_side} 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
        <limit effort="${limit_effort}" velocity="${limit_velocity}"/>
    </joint>
    <link name="front_right_wheel">
        <collision>
            <geometry>
                <cylinder length="${wheel_length * collision_multiplier}" radius="${wheel_radius}" />
            </geometry>
        </collision>
        <visual>
            <origin xyz="0 0 ${wheel_length/2}" rpy="-${pi/2} 0 0"/>
            <geometry>
                <mesh filename="${wheel_mesh_file}" scale="${mesh_scale}" />
            </geometry>
            <material name="gray"/>
        </visual>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Rear Left Wheel -->
    <joint name="rear_left_wheel_joint" type="continuous">
        <parent link="chassis"/>
        <child link="rear_left_wheel"/>
        <origin xyz="${wheel_offset_rear} ${wheel_offset_side} 0" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
        <limit effort="${limit_effort}" velocity="${limit_velocity}"/>
    </joint>
    <link name="rear_left_wheel">
        <collision>
            <geometry>
                <cylinder length="${wheel_length * collision_multiplier}" radius="${wheel_radius}" />
            </geometry>
        </collision>
        <visual>
            <origin xyz="0 0 ${wheel_length/2}" rpy="-${pi/2} 0 0"/>
            <geometry>
                <mesh filename="${wheel_mesh_file}" scale="${mesh_scale}" />
            </geometry>
            <material name="gray"/>
        </visual>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Rear Right Wheel -->
    <joint name="rear_right_wheel_joint" type="continuous">
        <parent link="chassis"/>
        <child link="rear_right_wheel"/>
        <origin xyz="${wheel_offset_rear} -${wheel_offset_side} 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
        <limit effort="${limit_effort}" velocity="${limit_velocity}"/>
    </joint>
    <link name="rear_right_wheel">
        <collision>
            <geometry>
                <cylinder length="${wheel_length * collision_multiplier}" radius="${wheel_radius}" />
            </geometry>
        </collision>
        <visual>
            <origin xyz="0 0 ${wheel_length/2}" rpy="-${pi/2} 0 0"/>
            <geometry>
                <mesh filename="${wheel_mesh_file}" scale="${mesh_scale}" />
            </geometry>
            <material name="gray"/>
        </visual>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Bucket Frame -->
    <joint name="bucket_frame_joint" type="fixed">
        <parent link="chassis"/>
        <child link="bucket_frame"/>
        <origin xyz="${chassis_length/4 + 0.0381} -0.00635 ${wheel_radius + 0.0277}" rpy="0 0 0"/>
    </joint>
    <link name="bucket_frame">
        <collision>
            <geometry>
                <box size="${bucket_frame_length * collision_multiplier} ${bucket_frame_width * collision_multiplier} ${bucket_frame_height}"/>
            </geometry>
            <material name="gray"/>
        </collision>
        <visual>
            <geometry>
                <mesh filename="file://$(find osprey_ros)/meshes/robot24/exc_dep_frame.dae" scale="${mesh_scale}" />
            </geometry>
            <material name="gray"/>
        </visual>
        <xacro:inertial_box mass="0.05" x="${bucket_frame_length}" y="${bucket_frame_width}" z="${bucket_frame_height}">
            <origin xyz="0 0 ${bucket_frame_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- Dig/Dump Bucket -->
    <joint name="bucket_joint" type="prismatic">
        <parent link="bucket_frame"/>
        <child link="bucket"/>
        <limit lower="-1"  upper="2"  velocity="0.1"  effort="${limit_effort}"  />
        <axis xyz="0 0 1"/>
        <origin xyz="-${bucket_length/2 + bucket_frame_length/2} 0 -${bucket_height/2}" rpy="0 0 0"/>
    </joint>
    <link name="bucket">
        <collision>
            <geometry>
                <box size="${bucket_length} ${bucket_width} ${bucket_height}"/>
            </geometry>
        </collision>
        <visual>
            <geometry>
                <mesh filename="file://$(find osprey_ros)/meshes/robot24/bucket.dae" scale="${mesh_scale}" />
            </geometry>
            <material name="gray"/>
        </visual>
        <xacro:inertial_box mass="0.1" x="${bucket_length}" y="${bucket_width}" z="${bucket_height}">
            <origin xyz="${chassis_length/2} 0 ${bucket_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- 360 Lidar -->
    <joint name="lidar_joint" type="fixed">
        <parent link="chassis"/>
        <child link="lidar"/>
        <axis xyz="0 0 1"/>
        <origin xyz="-${chassis_length/2} 0 0.4572" rpy="0 0 0"/>
    </joint>
    <link name="lidar">
        <collision>
            <geometry>
                <box size="${lidar_length} ${lidar_width} ${lidar_height}"/>
            </geometry>
        </collision>
        <visual>
            <geometry>
                <mesh filename="file://$(find osprey_ros)/meshes/rplidar.dae" scale="1 1 1" />
            </geometry>
            <material name="black"/>
        </visual>
        <xacro:inertial_box mass="0.0001" x="${lidar_length}" y="${lidar_width}" z="0.6096">
            <origin xyz="${lidar_length/2} ${lidar_width/2} 0.6096" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- 3D Camera -->
    <joint name="depth_camera_joint" type="fixed">
        <parent link="chassis"/>
        <child link="depth_camera"/>
        <origin xyz="${chassis_length/2 + 0.0254} 0 0" rpy="0 0 0"/>
    </joint>
    <link name="depth_camera">
        <visual>
            <geometry>
                <box size="0.010 0.03 0.03"/>
            </geometry>
            <material name="black"/>
        </visual>
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <cylinder radius="0.002" length="0.1"/>
            </geometry>
        </visual>
    </link>

</robot>
