<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="limit_effort" value="100" />
    <xacro:property name="limit_velocity" value="10" />

    <!-- Values in meters -->
    <xacro:property name="bucket_length" value="0.3556" /> <!-- depth -->
    <xacro:property name="bucket_height" value="0.254" />
    <xacro:property name="bucket_width" value="0.254" />

    <xacro:property name="bucket_ladder_scale" value="1 1 1" />
    <xacro:property name="bucket_ladder_rpy" value="-${pi/2} ${pi/2} 0" />
    <xacro:property name="bucket_ladder_xyz" value="${buckets_length} -${ladder_width + wheel_gap/4} ${buckets_height - chassis_height/1.25}" />

    <xacro:property name="buckets_length" value="0.254" /> <!-- depth -->
    <xacro:property name="buckets_height" value="0.9144" />
    <xacro:property name="buckets_width" value="0.1778" />

    <xacro:property name="chassis_length" value="0.8128" />
    <xacro:property name="chassis_height" value="0.0889" />
    <xacro:property name="chassis_width" value="0.3556" />

    <xacro:property name="ladder_length" value="0.0508" /> <!-- depth -->
    <xacro:property name="ladder_height" value="0.7874" />
    <xacro:property name="ladder_width" value="${chassis_width}" />
    <xacro:property name="ladder_offset" value="${chassis_length/2 + buckets_width/10}" />
    <xacro:property name="ladder_xyz" value="${buckets_length} -${ladder_width + wheel_gap/4} ${buckets_height - chassis_height/2}" />

    <xacro:property name="lidar_length" value="0.12954" />
    <xacro:property name="lidar_height" value="0.07874" />
    <xacro:property name="lidar_width" value="0.09906" />

    <xacro:property name="wheel_gap" value="0.0127" />
    <xacro:property name="wheel_length" value="0.1016" />
    <xacro:property name="wheel_radius" value="0.1524" />
    <xacro:property name="wheel_mass" value="0.0624" />
    <xacro:property name="wheel_mesh_file" value="file://$(find osprey_ros)/meshes/wheel.dae" />
    <xacro:property name="wheel_mesh_scale" value="0.001 0.001 0.001" />
    <xacro:property name="wheel_offset_front" value="${-chassis_length/2 + 0.1778}" />
    <xacro:property name="wheel_offset_rear" value="${chassis_length/2 - 0.2286}" />
    <xacro:property name="wheel_offset_side" value="${wheel_length/2 + chassis_width/2 + wheel_gap}" />

    <link name="base_link"></link>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
    </joint>
    <link name="base_footprint">
        <parent link="base_link"/>
    </link>

    <!-- Main Body/Chassis -->
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
        <child link="chassis"/>
    </joint>
    <link name="chassis">
        <collision>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="-${chassis_length/2} ${chassis_length/2 - chassis_height - wheel_gap/2} -${chassis_width/2}" rpy="${pi/2} 0 0"/>
            <geometry>
                <mesh filename="file://$(find osprey_ros)/meshes/chassis.dae" scale="0.8 0.8 0.8" />
            </geometry>
            <material name="gray"/>
        </visual>
        <xacro:inertial_box mass="2.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- Front Left Wheel -->
    <joint name="front_left_wheel_joint" type="continuous">
        <parent link="chassis"/>
        <child link="front_left_wheel"/>
        <origin xyz="${wheel_offset_front} ${wheel_offset_side} 0" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
        <limit effort="${limit_effort}" velocity="${limit_velocity}"/>
    </joint>
    <link name="front_left_wheel">
        <collision>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
            </geometry>
        </collision>
        <visual>
            <origin xyz="-${wheel_radius} -${wheel_radius} ${wheel_length/2}" rpy="-${pi/2} 0 0"/>
            <geometry>
                <mesh filename="${wheel_mesh_file}" scale="${wheel_mesh_scale}" />
            </geometry>
            <material name="gray"/>
        </visual>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Front Right Wheel -->
    <joint name="front_right_wheel_joint" type="continuous">
        <parent link="chassis"/>
        <child link="front_right_wheel"/>
        <origin xyz="${wheel_offset_front} -${wheel_offset_side} 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
        <limit effort="${limit_effort}" velocity="${limit_velocity}"/>
    </joint>
    <link name="front_right_wheel">
        <collision>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
            </geometry>
        </collision>
        <visual>
            <origin xyz="-${wheel_radius} ${wheel_radius} -${wheel_length/2}" rpy="${pi/2} 0 0"/>
            <geometry>
                <mesh filename="${wheel_mesh_file}" scale="${wheel_mesh_scale}" />
            </geometry>
            <material name="gray"/>
        </visual>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Rear Left Wheel -->
    <joint name="rear_left_wheel_joint" type="continuous">
        <parent link="chassis"/>
        <child link="rear_left_wheel"/>
        <origin xyz="${wheel_offset_rear} ${wheel_offset_side} 0" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
        <limit effort="${limit_effort}" velocity="${limit_velocity}"/>
    </joint>
    <link name="rear_left_wheel">
        <collision>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
            </geometry>
        </collision>
        <visual>
            <origin xyz="-${wheel_radius} -${wheel_radius} ${wheel_length/2}" rpy="-${pi/2} 0 0"/>
            <geometry>
                <mesh filename="${wheel_mesh_file}" scale="${wheel_mesh_scale}" />
            </geometry>
            <material name="gray"/>
        </visual>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Rear Right Wheel -->
    <joint name="rear_right_wheel_joint" type="continuous">
        <parent link="chassis"/>
        <child link="rear_right_wheel"/>
        <origin xyz="${wheel_offset_rear} -${wheel_offset_side} 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
        <limit effort="${limit_effort}" velocity="${limit_velocity}"/>
    </joint>
    <link name="rear_right_wheel">
        <collision>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
            </geometry>
        </collision>
        <visual>
            <origin xyz="-${wheel_radius} ${wheel_radius} -${wheel_length/2}" rpy="${pi/2} 0 0"/>
            <geometry>
                <mesh filename="${wheel_mesh_file}" scale="${wheel_mesh_scale}" />
            </geometry>
            <material name="gray"/>
        </visual>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Bucket Ladder Guide Frame -->
    <joint name="bucket_ladder_frame_joint" type="revolute">
        <parent link="chassis"/>
        <child link="guide_frame"/>
        <limit lower="-0.523598775598"  upper="0"  velocity="0.1"  effort="${limit_effort}"  />
        <axis xyz="0 1 0"/>
        <origin xyz="${ladder_offset} 0 0" rpy="0 0 0"/>
    </joint>
    <link name="guide_frame">
        <collision>
            <origin xyz="0 0 ${ladder_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${ladder_length} ${ladder_width} ${ladder_height}"/>
            </geometry>
            <material name="gray"/>
        </collision>
        <visual>
            <origin xyz="${bucket_ladder_xyz}" rpy="${bucket_ladder_rpy}"/>
            <geometry>
                <mesh filename="file://$(find osprey_ros)/meshes/bucket_ladder_guide_frame.dae" scale="${bucket_ladder_scale}" />
            </geometry>
            <material name="gray"/>
        </visual>
        <xacro:inertial_box mass="0.05" x="${ladder_length}" y="${ladder_width}" z="${ladder_height}">
            <origin xyz="0 0 ${ladder_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- Bucket Ladder Lift -->
    <joint name="bucket_ladder_lift_joint" type="prismatic">
        <parent link="guide_frame"/>
        <child link="lift"/>
        <limit lower="-0.35"  upper="0"  velocity="0.1"  effort="${limit_effort}"  />
        <axis xyz="0 0 1"/>
    </joint>
    <link name="lift">
        <collision>
            <origin xyz="0 0 ${ladder_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${ladder_length} ${ladder_width} ${ladder_height}"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="${ladder_xyz}" rpy="${bucket_ladder_rpy}"/>
            <geometry>
                <mesh filename="file://$(find osprey_ros)/meshes/bucket_ladder_lift_frame.dae" scale="${bucket_ladder_scale}" />
            </geometry>
            <material name="gray"/>
        </visual>
        <xacro:inertial_box mass="0.01" x="${ladder_length}" y="${ladder_width}" z="${ladder_height}">
            <origin xyz="0 0 ${ladder_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- Bucket Ladder Buckets -->
    <joint name="bucket_ladder_buckets_joint" type="continuous">
        <parent link="lift"/>
        <child link="buckets"/>
        <axis xyz="0 0 1"/>
    </joint>
    <link name="buckets">
        <collision>
            <origin xyz="0 0 ${ladder_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${buckets_length} ${buckets_width} ${buckets_height}"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="${ladder_xyz}" rpy="${bucket_ladder_rpy}"/>
            <geometry>
                <mesh filename="file://$(find osprey_ros)/meshes/bucket_ladder_gears.dae" scale="${bucket_ladder_scale}" />
            </geometry>
            <material name="gray"/>
        </visual>
        <xacro:inertial_box mass="0.01" x="${buckets_length}" y="${buckets_width}" z="${buckets_height}">
            <origin xyz="0 0 ${ladder_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="bucket_dump_joint" type="prismatic">
        <parent link="chassis"/>
        <child link="bucket"/>
        <limit lower="0"  upper="2"  velocity="0.1"  effort="${limit_effort}"  />
        <axis xyz="0 0 1"/>
        <origin xyz="${bucket_length/2} 0 ${bucket_height/2 + chassis_height}" rpy="0 0 0"/>
    </joint>
    <link name="bucket">
        <collision>
            <geometry>
                <box size="${bucket_length} ${bucket_width} ${bucket_height}"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="${bucket_length/2} -${bucket_width/1.6} -${chassis_height}" rpy="${pi/2} 0 ${pi}"/>
            <geometry>
                <mesh filename="file://$(find osprey_ros)/meshes/dump_bucket_body.dae" scale="0.065 0.065 0.065" />
            </geometry>
            <material name="gray"/>
        </visual>
        <xacro:inertial_box mass="0.1" x="${bucket_length}" y="${bucket_width}" z="${bucket_height}">
            <origin xyz="${chassis_length/2} 0 ${bucket_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="lidar_joint" type="fixed">
        <parent link="guide_frame"/>
        <child link="lidar"/>
        <axis xyz="0 0 1"/>
        <origin xyz="${ladder_length/1.5} 0 ${ladder_height + lidar_height}" rpy="0 0 0"/>
    </joint>
    <link name="lidar">
        <collision>
            <geometry>
                <box size="${lidar_length} ${lidar_width} ${lidar_height}"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="file://$(find osprey_ros)/meshes/rplidar.dae" scale="1 1 1" />
            </geometry>
            <material name="gray"/>
        </visual>
        <xacro:inertial_box mass="0.0001" x="${lidar_length}" y="${lidar_width}" z="${ladder_height}">
            <origin xyz="${lidar_length/2} ${lidar_width/2} ${ladder_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
    <gazebo reference="lidar">
        <sensor name="lidar_sensor" type="gpu_lidar">
            <pose>0 0 0 0 0 0</pose>
            <topic>lidar</topic>
            <update_rate>10</update_rate>
            <lidar>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                        <resolution>1</resolution>
                    </horizontal>
                </scan>
                <range>
                    <min>0.3</min>
                    <max>12</max>
                    <resolution>0.01</resolution>
                </range>
            </lidar>
            <always_on>1</always_on>
            <visualize>true</visualize>
        </sensor>
    </gazebo>

</robot>
