<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="limit_effort" value="100" />
    <xacro:property name="limit_velocity" value="1" />

    <!-- Values in meters -->
    <xacro:property name="chassis_length" value="0.762" />
    <xacro:property name="chassis_height" value="0.0889" />
    <xacro:property name="chassis_width" value="0.368" />
    <xacro:property name="wheel_length" value="0.1" />
    <xacro:property name="wheel_radius" value="0.15" />

    <link name="base_link"></link>

    <!-- Main Body/Chassis -->
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="-0.1 0 0"/>
    </joint>
    <link name="chassis">
        <collision>
            <origin xyz="0.0935 0 0.00" rpy="0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="${chassis_length/2} 0 0.00" rpy="0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 0.04675" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- Front Left Wheel -->
    <joint name="front_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="front_left_wheel"/>
        <origin xyz="-0.0585 0.0725 0" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
        <limit effort="${limit_effort}" velocity="${limit_velocity}"/>
    </joint>
    <link name="front_left_wheel">
        <collision>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
            </geometry>
        </collision>
        <visual>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
            </geometry>
            <material name="yellow"/>
        </visual>
        <xacro:inertial_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Front Right Wheel -->
    <joint name="front_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="front_right_wheel"/>
        <origin xyz="-0.0585 -0.0725 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
        <limit effort="${limit_effort}" velocity="${limit_velocity}"/>
    </joint>
    <link name="front_right_wheel">
        <collision>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
            </geometry>
        </collision>
        <visual>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
            </geometry>
            <material name="yellow"/>
        </visual>
        <xacro:inertial_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Rear Left Wheel -->
    <joint name="rear_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="rear_left_wheel"/>
        <origin xyz="0.062 0.0725 0" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
        <limit effort="${limit_effort}" velocity="${limit_velocity}"/>
    </joint>
    <link name="rear_left_wheel">
        <collision>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
            </geometry>
        </collision>
        <visual>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
            </geometry>
            <material name="yellow"/>
        </visual>
        <xacro:inertial_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Rear Right Wheel -->
    <joint name="rear_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="rear_right_wheel"/>
        <origin xyz="0.062 -0.0725 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
        <limit effort="${limit_effort}" velocity="${limit_velocity}"/>
    </joint>
    <link name="rear_right_wheel">
        <collision>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
            </geometry>
        </collision>
        <visual>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
            </geometry>
            <material name="yellow"/>
        </visual>
        <xacro:inertial_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

</robot>
