<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="limit_effort" value="100" />
    <xacro:property name="limit_velocity" value="1" />

    <!-- Values in meters -->
    <xacro:property name="buckets_length" value="0.254" /> <!-- depth -->
    <xacro:property name="buckets_height" value="0.9144" />
    <xacro:property name="buckets_width" value="0.1778" />

    <xacro:property name="chassis_length" value="0.8128" />
    <xacro:property name="chassis_height" value="0.0889" />
    <xacro:property name="chassis_width" value="0.3556" />

    <xacro:property name="ladder_length" value="0.0508" /> <!-- depth -->
    <xacro:property name="ladder_height" value="0.7874" />
    <xacro:property name="ladder_width" value="${chassis_width}" />
    <xacro:property name="ladder_offset" value="${-chassis_length/2 - buckets_length/2 - 0.0127}" />

    <xacro:property name="wheel_length" value="0.1016" />
    <xacro:property name="wheel_radius" value="0.1524" />
    <xacro:property name="wheel_mesh_file" value="package://osprey_ros/meshes/wheel.dae" />
    <xacro:property name="wheel_mesh_scale" value="0.001 0.001 0.001" />
    <xacro:property name="wheel_offset_front" value="${-chassis_length/2 + 0.1778}" />
    <xacro:property name="wheel_offset_rear" value="${chassis_length/2 - 0.2286}" />
    <xacro:property name="wheel_offset_side" value="${wheel_length/2 + chassis_width/2 + 0.0127}" />

    <link name="base_link"></link>

    <!-- Main Body/Chassis -->
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
    </joint>
    <link name="chassis">
        <collision>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <visual>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- Front Left Wheel -->
    <joint name="front_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="front_left_wheel"/>
        <origin xyz="${wheel_offset_front} -${wheel_offset_side} 0" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
        <limit effort="${limit_effort}" velocity="${limit_velocity}"/>
    </joint>
    <link name="front_left_wheel">
        <collision>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
            </geometry>
        </collision>
        <visual>
            <origin xyz="-${wheel_radius} ${wheel_radius} -${wheel_length/2}" rpy="${pi/2} 0 0"/>
            <geometry>
                <mesh filename="${wheel_mesh_file}" scale="${wheel_mesh_scale}" />
            </geometry>
        </visual>
        <xacro:inertial_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Front Right Wheel -->
    <joint name="front_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="front_right_wheel"/>
        <origin xyz="${wheel_offset_front} ${wheel_offset_side} 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
        <limit effort="${limit_effort}" velocity="${limit_velocity}"/>
    </joint>
    <link name="front_right_wheel">
        <collision>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
            </geometry>
        </collision>
        <visual>
            <origin xyz="-${wheel_radius} -${wheel_radius} ${wheel_length/2}" rpy="-${pi/2} 0 0"/>
            <geometry>
                <mesh filename="${wheel_mesh_file}" scale="${wheel_mesh_scale}" />
            </geometry>
        </visual>
        <xacro:inertial_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Rear Left Wheel -->
    <joint name="rear_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="rear_left_wheel"/>
        <origin xyz="${wheel_offset_rear} -${wheel_offset_side} 0" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
        <limit effort="${limit_effort}" velocity="${limit_velocity}"/>
    </joint>
    <link name="rear_left_wheel">
        <collision>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
            </geometry>
        </collision>
        <visual>
            <origin xyz="-${wheel_radius} ${wheel_radius} -${wheel_length/2}" rpy="${pi/2} 0 0"/>
            <geometry>
                <mesh filename="${wheel_mesh_file}" scale="${wheel_mesh_scale}" />
            </geometry>
        </visual>
        <xacro:inertial_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Rear Right Wheel -->
    <joint name="rear_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="rear_right_wheel"/>
        <origin xyz="${wheel_offset_rear} ${wheel_offset_side} 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
        <limit effort="${limit_effort}" velocity="${limit_velocity}"/>
    </joint>
    <link name="rear_right_wheel">
        <collision>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
            </geometry>
        </collision>
        <visual>
            <origin xyz="-${wheel_radius} -${wheel_radius} ${wheel_length/2}" rpy="-${pi/2} 0 0"/>
            <geometry>
                <mesh filename="${wheel_mesh_file}" scale="${wheel_mesh_scale}" />
            </geometry>
        </visual>
        <xacro:inertial_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Bucket Ladder Lift -->
    <joint name="bucket_ladder_lift_joint" type="prismatic">
        <parent link="base_link"/>
        <child link="lift"/>
        <limit lower="0"  upper="2"  velocity="0.1"  effort="${limit_effort}"  />
        <axis xyz="0 0 1"/>
        <origin xyz="${ladder_offset} 0 0" rpy="0 0 0"/>
    </joint>
    <link name="lift">
        <collision>
            <origin xyz="0 0 ${ladder_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${ladder_length} ${ladder_width} ${ladder_height}"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="0 0 ${ladder_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${ladder_length} ${ladder_width} ${ladder_height}"/>
            </geometry>
            <material name="green"/>
        </visual>
        <xacro:inertial_box mass="0.5" x="${ladder_length}" y="${ladder_width}" z="${ladder_height}">
            <origin xyz="0 0 ${ladder_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- Bucket Ladder Buckets -->
    <joint name="bucket_ladder_buckets_joint" type="continuous">
        <parent link="lift"/>
        <child link="buckets"/>
        <axis xyz="0 0 1"/>
    </joint>
    <link name="buckets">
        <collision>
            <origin xyz="0 0 ${ladder_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${buckets_length} ${buckets_width} ${buckets_height}"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="0 0 ${ladder_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${buckets_length} ${buckets_width} ${buckets_height}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <xacro:inertial_box mass="0.5" x="${buckets_length}" y="${buckets_width}" z="${buckets_height}">
            <origin xyz="0 0 ${ladder_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

</robot>
