controller_manager:
  ros__parameters:
    update_rate: 10

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    gpio_controller:
      type: gpio_controller/GPIOController

    position_controllers:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controllers:
      type: velocity_controllers/JointGroupVelocityController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ['front_left_wheel_joint', 'rear_left_wheel_joint']
    right_wheel_names: ['front_right_wheel_joint', 'rear_right_wheel_joint']
    wheels_per_side: 2
    wheel_separation: 1.0 # 0.3683
    wheel_radius: 0.1524

    odom_frame_id: odom
    base_frame_id: base_link

    enable_odom_tf: true

    use_stamped_vel: false

gpio_controller:
  ros__parameters:
    inputs:
     - actuator/relay_1
     - actuator/relay_2
     - limit_switch/bucket_ladder_top
     - limit_switch/bucket_ladder_bottom
     - limit_switch/bucket_dump_front
     - limit_switch/bucket_dump_back
     - limit_switch/actuator_extended
    outputs:
     - actuator/relay_1
     - actuator/relay_2

position_controllers:
  ros__parameters:
    joints:
      - bucket_dump_joint
      - bucket_ladder_frame_joint
      - bucket_ladder_lift_joint

velocity_controllers:
  ros__parameters:
    joints:
      - bucket_ladder_buckets_joint
