controller_manager:
  ros__parameters:
    update_rate: 10

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_position_controller:
      type: position_controllers/JointPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ['front_left_wheel_joint', 'rear_left_wheel_joint']
    right_wheel_names: ['front_right_wheel_joint', 'rear_right_wheel_joint']
    wheels_per_side: 2
    wheel_separation: 0.192
    wheel_radius: 0.0325

    odom_frame_id: odom
    base_frame_id: base_link

    enable_odom_tf: true

    use_stamped_vel: false

joint_position_controller:
  ros__parameters:
    joints:
      - bucket_dump_joint
      - bucket_ladder_lift_joint

joint_velocity_controller:
  ros__parameters:
    joints:
      - bucket_ladder_buckets_joint
